### ISSUE TITLE
BCPA not on cran anymore

### ISSUE THREAD

**Issue by bart1** [EliGurarie/bcpa#1]
The removal of `BCPA` from cran causes issues in package checks (e.g.: https://www.r-project.org/nosvn/R.check/r-release-linux-x86_64/move-00check.html ). Is there a plan to have the back package on cran soon?

**Comment by EliGurarie** [comment]
Thanks for letting me know.  I wasn't aware ... will dig in and see what can be done.  There may be a back-dependency issue.

**Comment by bart1** [comment]
Thanks do you have a idea when you would be able to get around this? (I need to make sure move does not get removed from CRAN before the end of the month)

**Comment by EliGurarie** [comment]
today

**Comment by bart1** [comment]
Thanks for the effort!

**Comment by EliGurarie** [comment]
bcpa back on CRAN: https://cran.r-project.org/web/packages/bcpa/index.html
